name: fresume_app
description: Make your free resume now!


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.0.18
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.5
  responsive_framework: ^1.1.1
  pdf: ^3.6.5
  flutter_riverpod: ^2.4.0
  get: ^4.3.8
  freezed_annotation: ^2.4.1
  freezed: ^2.4.2
  build_runner: ^2.0.4
  intl: ^0.18.1
  pdf_render: ^1.0.19
  printing: ^5.3.0
  universal_html: ^2.0.8
  
  google_fonts: ^6.0.0
  json_serializable: ^6.7.1
  adaptive_theme: ^3.4.0
  uuid: ^4.0.0
  cloud_firestore: ^4.9.2
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  firebase_database: ^10.2.6
  flutterfire_ui: ^0.4.3+20
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3

flutter:

  uses-material-design: true